[package]
name = "tc"
version = "1.0.1"
edition = "2024"
license = "MIT"
description = "A Rust clone of the GNU Coreutils `wc` command"
repository = "https://github.com/bephemeral/textcount"
readme = "README.md"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
tabled = "0.20.0"
